services:
  - type: web
    name: hyperlocal-economy-intelligence
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run "unisole_EDA/EDA Project/hyperlocal-economy-intelligence/app.py" --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
